### ISSUE TITLE
Support generics interfacing by returning `[]*ErrorsItem` instead of `[]ErrorsItem`

### ISSUE THREAD

**Issue by adrianlungu** [ogen-go/ogen#1008]
Hello,

Was trying to create a way to handle the errors generated by ogen without having to go one by one through each of them via the following code:

```
type HTTPError[EI ErrorItem] interface {
	GetErrors() []EI
}

type ErrorItem interface {
	GetTitle() ogen.OptString
}

func handleErrors[EI ErrorItem, HT HTTPError[EI]](resp HT) error {
	var errs error

	for _, err := range resp.GetErrors() {
		if err.GetTitle().IsSet() {
			errs = errors.Wrap(errs, err.GetTitle().Value)
		}
	}

	return errs
}
```

However, due to the `GetErrors()` returning `[]ErrorItem` instead of `[]*ErrorItem`, it seems to not be possible currently to easily use such an abstraction. 

Would it be feasible to return a slice to pointers instead of slice to the value ?

Thanks!

**Comment by tdakkota** [comment]
[You can do something like this:](https://go.dev/play/p/WCMvivRtXJn)
```go
func handleErrors[
	Error any, 
	PError interface {
		*Error
		ErrorItem
	},
	Resposne interface {
		GetErrors() []Error
	},
](resp Resposne) error {
	var errs error

	for _, err := range resp.GetErrors() {
		perr := PError(&err)
		if perr.GetTitle().IsSet() {
			fmt.Println(perr.GetTitle().Value)
		}
	}

	return errs
}
```

**Comment by adrianlungu** [comment]
And I just discovered that JetBrains doesn't yet have full support for Go Generics and I was getting errors that were not actually errors according to Go 😅 

Thanks @tdakkota , that does the trick!
