### ISSUE TITLE
Breaking changes in oneOf schemas, accepted or mistake?

### ISSUE THREAD

**Issue by dan-j** [ogen-go/ogen#1012]
### What version of ogen are you using?

```bash
$ go list -m github.com/ogen-go/ogen
```

v0.73.0

### Can this issue be reproduced with the latest version?

Yes

### What did you do?

I've just tried to upgrade to 0.73.0 and running into big breaking changes with the generated code since the solution to #960. 

Say you have `Vehicle` which can be `oneOf`, `Car` or `Bicycle`, in 0.71.1 the generated `Vehicle` struct would be as follows:

```go
type Vehicle struct {
  Type VehicleType
  Car Car
  Bicycle Bycycle
}
```

Whereas in 0.73.0 this is output:

```go
type Vehicle struct {
  OneOf VehicleSum
}
```

And `VehicleSum` contains the `Type`, `Car`, and `Bicycle` fields.

Was this intended? The API surface prior to this change was nice but now it feels like I have structs implemented in a way to fit around the library, rather than my structs modelling my actual data.

**Comment by dan-j** [comment]
Just to add to this, I've noticed the docs website is also still describing the old behaviour. If the latest changes are decided to be on purpose, the docs will need updating: https://ogen.dev/docs/types/sumtype

**Comment by ernado** [comment]
Please check that your schema does not contain the `type: object` part, like:

```yaml
Sum:
  type: object # <-- HERE
  oneOf:
    - $ref: '#/components/schemas/Cat'
    - $ref: '#/components/schemas/Dog'
  discriminator:
    propertyName: petType
    mapping:
      cat: '#/components/schemas/Cat'
      dog: '#/components/schemas/Dog'
```

If such, please try removing it.

**Comment by dan-j** [comment]
ah ha! That works, thanks
