### ISSUE TITLE
bug: Compatability with 1.16

### ISSUE THREAD

**Issue by masseelch** [ogen-go/ogen#102]
The change introduced in [this commit](https://github.com/ogen-go/ogen/commit/8904bc2040b61c2ed2d2129e42dabd0ac1e43d01) break compatibility with Go 1.16.

I think it is good practice to support the last two versions of Go, since the Go team does the same.

To give context: This is the feature introduced with 1.17.
https://tip.golang.org/ref/spec#Conversions_from_slice_to_array_pointer

**Comment by ernado** [comment]
Go 1.18 will be released next month, so last two will be 1.17 and 1.18.

IMO it is ok to drop 1.16.

**Comment by masseelch** [comment]
Well, kind of true :+1:
