### ISSUE TITLE
Unauthorized error trying to run ogen using by Docker

### ISSUE THREAD

**Issue by waffleboot** [ogen-go/ogen#1092]
### What did you do?

I try to run docker command from README:

```bash
docker run --rm \
  --volume ".:/workspace" \
  ghcr.io/ogen-go/ogen:latest --target workspace/petstore --clean workspace/petstore.yml
```

### What did you expect to see?

Succeed operation

### What did you see instead?

```
Unable to find image 'ghcr.io/ogen-go/ogen:latest' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/ogen-go/ogen/manifests/latest": unauthorized.
See 'docker run --help'.
```

**Comment by gvencadze** [comment]
@ernado hey, can you pls enable container registry in project settings? Probably it should resolve problem

**Comment by tdakkota** [comment]
Image has public visibility now.

Closing as fixed.
