### ISSUE TITLE
Ogen generated code instruments OTEL Http Metrics following semantic conventions

### ISSUE THREAD

**Issue by kkawakami-cybozu** [ogen-go/ogen#1128]
### Description

Would like to have the ogen generated code instrument metrics that are currently marked as **stable** in [Semantic Conventions for HTTP Metrics](https://opentelemetry.io/docs/specs/semconv/http/http-metrics/) 
- `http.server.request.duration`
- `http.client.request.duration`

### References

- https://opentelemetry.io/docs/specs/semconv/http/http-metrics/

**Comment by ernado** [comment]
Please use `go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp` for metrics that follow semantic conventions, they will work perferctly with ogen.

I will update [ogen/example](https://github.com/ogen-go/example) repo with more details like using `LabelerFromContext` and `WithSpanNameFormatter` with ogen.

Thank you for bringing this issue.

**Comment by ernado** [comment]
For now please refer to

https://github.com/ogen-go/example/blob/4391e6af6a14aed4442ede1cfc355b19188ad763/cmd/api-server/main.go#L41-L52
https://github.com/ogen-go/example/blob/4391e6af6a14aed4442ede1cfc355b19188ad763/internal/httpmiddleware/httpmiddleware.go#L84-L102
