### ISSUE TITLE
feat(gen): client request editor

### ISSUE THREAD

**Issue by tdakkota** [ogen-go/ogen#1138]
### Discussed in https://github.com/ogen-go/ogen/discussions/1135

<div type='discussions-op-text'>

<sup>Originally posted by **StringNick** December 12, 2023</sup>
I tried to research how i can integrate change header or add some logger as server middleware to client library in dev environments, and i researched now it's not possible, so is it possible to add something like oapi-codegen for client generated code, for editing request (for example add custom header, and etc).
Example editor for special route and call:
<img width="767" alt="image" src="https://github.com/ogen-go/ogen/assets/13052752/993e3c3e-a279-4a20-a6e6-52260c0af631">
Example of global request editor for all calls:
```go
client, clientErr := NewClient("", WithRequestEditorFn(someHeaderOrLogEditor))
```
It can help to add logger, to add custom debug headers that u cant specify in spec and etc.
Without this configuration its inpossible to use generator for client in my project, for server i saw solution about abstract on server interface, but for client nothing.
Thank you for attention</div>

**Comment by tdakkota** [comment]
I think, per-operation `RequestEditor` is fine as an opt-in feature (e.g. `ogen/client/request_editors`).

**Comment by slangens1** [comment]
You can already edit request headers using WithClient which has the signature `Do(r *http.Request) (*http.Response, error)`

Why else would this be needed?
