### ISSUE TITLE
Generator: Incorrect JSON Marshaller for Optional types if optional field is not set

### ISSUE THREAD

**Issue by artlo** [ogen-go/ogen#1190]
### What version of ogen are you using?

```bash
$ go list -m github.com/ogen-go/ogen
```

`github.com/ogen-go/ogen v0.82.0`

### Can this issue be reproduced with the latest version?
Yes

### What did you do?
Initiaite the optional parameter `OptParameter` and make `json.Marshal` for that. The following error is occured: `error calling MarshalJSON for type OptParameter: unexpected end of JSON input `

generated code:
```
type Parameters struct {
    ValueOne OptParameter
}

func (s OptParameter) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// Encode encodes int as json.
func (o OptParameter) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	e.Str(string(o.Value))
}
```

code base:
```
p := Parameters{}
b, err := json.Marshal(p)
```
The code above produce error `error calling MarshalJSON for type OptParameter: unexpected end of JSON input `
It's produced because the Encode method set nothing to Encoder, so in JSONMarshal `e.Bytes` returns nil, so the json has incorrect representation

### What did you expect to see?
The JSON should be generated for not initiated Optional parameter with default values. For example above, it should be:
`{"ValueOne":""}` or `{"ValueOne": nil} (preferable, because default value can be valid valie) or extend json for optional field with SET parameter

### What did you see instead?
The json marshaling error

**Comment by ernado** [comment]
For `ValueOne` key in
```json
{"ValueOne": ""}
```
Value is blank string.

For `ValueOne` key in
```json
{"ValueOne": null}
```
Value is `null`.


Both cases does not represent the "absence of value" case where the `ValueOne` key is not set.

**Comment by tdakkota** [comment]
I believe this is duplicate of #660.

**Comment by artlo** [comment]
Yes, it looks like the dup
