### ISSUE TITLE
[Misnamed Schema Object]: OpenAPI schema object name incorrectly being generated/used

### ISSUE THREAD

**Issue by PedroSoutoDev** [ogen-go/ogen#1202]
### What version of ogen are you using?
ogen version v1.0.0 (built with go1.22.1) linux/amd64

### Can this issue be reproduced with the latest version?
Yes

### What did you do?
1. Generate the OpenAPI schema (See Below)
2. `oas_interfaces_gen.go` generates this: 
```
// Code generated by ogen, DO NOT EDIT.
package api

type LoginAccountRes interface {
	loginAccountRes()
}
```

3. `oas_server_gen.go` generates this:
```
// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateAccount implements CreateAccount operation.
	//
	// Create a new account.
	//
	// POST /account/create
	CreateAccount(ctx context.Context, req *CreateAccountRequest) (*CreateAccountResponse, error)
	// LoginAccount implements LoginAccount operation.
	//
	// Login to an existing account.
	//
	// POST /account/login
	LoginAccount(ctx context.Context, req *LoginAccountRequest) (LoginAccountRes, error)
	// NewError creates *DefaultErrorResponseStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *DefaultErrorResponseStatusCode
}
...
```

4.  Unable to create a new server via the `NewServer` functions, with the following error:
```
cannot use accountHandler (variable of type handlers.AccountHandler) as api.Handler value in argument to api.NewServer: handlers.AccountHandler does not implement api.Handler (wrong type for method LoginAccount)
		have LoginAccount(context.Context, *api.LoginAccountRequest) (*api.LoginAccountResponse, error)
		want LoginAccount(context.Context, *api.LoginAccountRequest) (api.LoginAccountRes, error)
		compiler[InvalidIfaceAssign](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#InvalidIfaceAssign)
var accountHandler handlers.AccountHandler
```

### OpenAPI Schema
```
openapi: "3.0.0"
info:
  version: 1.0.0
  title: XYZ
  description: API for XYZ
  contact:
    name: XYZ
    email: admin@xyz.com
    url: http://xyz.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html


servers:
  - url: https://xyz.com/api/v1


paths:
  /account/create:
    post:
      tags:
        - Account
      description: Create a new account
      operationId: CreateAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountRequest'
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateAccountResponse'
        default:
          $ref: '#/components/responses/DefaultErrorResponse'

  /account/login:
    post:
      tags:
        - Account
      description: Login to an existing account
      operationId: LoginAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginAccountRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginAccountResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          $ref: '#/components/responses/DefaultErrorResponse'


components:
  responses:
    DefaultErrorResponse:
      description: Error, endpoint not implemented
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    CreateAccountRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
    CreateAccountResponse:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          format: uuid
    LoginAccountRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
    LoginAccountResponse:
      type: object
      required:
        - session
      properties:
        session:
          type: string
          format: uuid
    Error: 
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
```

### What did you expect to see?
`LoginAccountResponse` should not be renamed to `LogingAccountRes`, I am not sure if this is a bug or if I am incorrectly using/config ogen.

Thank you.

**Comment by k4n4ry** [comment]
When generating code, if the corresponding type cannot be uniquely determined due to reasons such as the existence of multiple response patterns, the return value of the endpoint method within the Handler will be set to an interface instead of a specific struct. 

In such cases, the name of the interface will not be the schema name, but rather the OperationID of the endpoint with the suffix `Res` appended to it. 

This results in the generation of an interface named `LoginAccountRes`, which is set as the return value for the response. I believe this is why you are seeing this interface being used.

If the response type can be determined (for example, if only the 200 pattern is set as shown below), a concrete struct will be set as the return value.

```yaml
  /account/login:
    post:
      tags:
        - Account
      description: Login to an existing account
      operationId: LoginAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginAccountRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginAccountResponse'
        default:
          $ref: '#/components/responses/DefaultErrorResponse'
```

`oas_server_gen.go`
```go
	// POST /account/login
	LoginAccount(ctx context.Context, req *LoginAccountRequest) (*LoginAccountResponse, error)
```

**Comment by k4n4ry** [comment]
When using interfaces, you should return a LoginAccountResponse within the implementation.
```go
// LoginAccount implements api.Handler.
func (HandlerImpl) LoginAccount(ctx context.Context, req *api.LoginAccountRequest) (api.LoginAccountRes, error) {
	ret := api.LoginAccountResponse{Session: uuid.Must(uuid.NewRandom())}
	return &ret, nil
}
```

**Comment by PedroSoutoDev** [comment]
> When generating code, if the corresponding type cannot be uniquely determined due to reasons such as the existence of multiple response patterns, the return value of the endpoint method within the Handler will be set to an interface instead of a specific struct.
> 
> In such cases, the name of the interface will not be the schema name, but rather the `operationId` of the endpoint with the suffix `Res` appended to it.
> 
> This results in the generation of an interface named `LoginAccountRes`, which is set as the return value for the response. I believe this is why you are seeing this interface being used.
> 
> If the response type can be determined (for example, if only the 200 pattern is set as shown below), a concrete struct will be set as the return value.
> 
> ```yaml
>   /account/login:
>     post:
>       tags:
>         - Account
>       description: Login to an existing account
>       operationId: LoginAccount
>       requestBody:
>         required: true
>         content:
>           application/json:
>             schema:
>               $ref: '#/components/schemas/LoginAccountRequest'
>       responses:
>         '200':
>           description: Success
>           content:
>             application/json:
>               schema:
>                 $ref: '#/components/schemas/LoginAccountResponse'
>         default:
>           $ref: '#/components/responses/DefaultErrorResponse'
> ```
> 
> `oas_server_gen.go`
> 
> ```go
> 	// POST /account/login
> 	LoginAccount(ctx context.Context, req *LoginAccountRequest) (*LoginAccountResponse, error)
> ```

So looking at my OpenAPI schema, is there any ways I can get it to always be "LoginAccountResposne".

It is not a good experience having different named schemas to work with. Will confusing for new devs on the project as well IMO.

**Comment by tdakkota** [comment]
`LoginAccountResponse` is not renamed to `LoginAccountRes`. It is just a coincidence.

`LoginAccountRes` is an [interface representing all response types of](https://ogen.dev/docs/concepts/interface_responses) operation `LoginAccount`.
If `LoginAccount` operation had `operaionId: login`, the response type would be named `LoginRes`.

**Comment by tdakkota** [comment]
I think we should this issue, since ogen works as intended.

CC @ernado

**Comment by PedroSoutoDev** [comment]
I have closed, since this doesnt seem to be an issue.

Thank you for the help so far! 
@tdakkota Can you help me understand why the same does not happen with CreateAccountResponse?

**Comment by tdakkota** [comment]
`CreateAccount` operation defines only one response, so there is no reason to generate an interface for response. 

`default` is generated from handler errors using `NewError` method. See [convenient errors](https://ogen.dev/docs/concepts/convenient_errors) feature section.
