### ISSUE TITLE
Incorrect generation of free-form objects

### ISSUE THREAD

**Issue by mxk** [ogen-go/ogen#1221]
[OpenAPI Guide](https://swagger.io/docs/specification/data-models/data-types/#free-form) states that `additionalProperties: true` is the default when a schema consists of just `type: object`, but the generated code ends up with a `struct{}` type unless `additionalProperties: true` is specified.

### What version of ogen are you using?

v1.0.1-0.20240411144324-e1628ac9f35f

### Can this issue be reproduced with the latest version?

Yes

### What did you do?

Changed schema from:

```json
"schema": {
  "type": "object"
}
```

to:

```json
"schema": {
  "type": "object"
  "additionalProperties": true
}
```

### What did you expect to see?

Generated code should be the same.

### What did you see instead?

Without `additionalProperties`:

```go
type MyApiReq struct{}
```

With `additionalProperties`:

```go
type MyApiReq map[string]jx.Raw
```

**Comment by dstubbersfield** [comment]
Bump. I got stung by this one too using latest OGEN, would be great to see a fix.

**Comment by tdakkota** [comment]
Current validator/decoder behavior matches expected by JSON Schema. 

ogen generates `AdditionalProps` only if  `additionalProperties` is defined explicitly.
Majority of schemas does not define `additionalProperties` and probably majority of users do not need them, so current behavior seems more reasonable for me.

#1246 fixes this issue in slighty different way: `AdditionalProps` would be added implicitly only if `properties` and `patternProperties` are not defined, but I still not convinced that any change is required.

@ernado Thoughts?

**Comment by ernado** [comment]
@tdakkota 

Let's generate `AdditionalProps` for `type: object` schema, the `struct{}` is pretty useless.
Will #1246 achieves this it is LGTM.

Also let's keep our default unchanged (do not generate `AdditionalProps` by default in other cases). If this will be a problem for someone, we can introduce a configuration option.
