### ISSUE TITLE
Client: valid json response decode error: "{" expected: unexpected byte 34 '"'

### ISSUE THREAD

**Issue by veqryn** [ogen-go/ogen#1315]
### What version of ogen are you using?
v1.4.1

### Can this issue be reproduced with the latest version?
Yes

### What did you do?
Generated a golang client, used it, received an error, and ogen wasn't able to decode the error.

Here is the openapi spec that generated ogen's client:
https://github.com/veqryn/awesome-go-api/blob/c737ba1703d2ca30be0d898b17717eca8c70565f/protobufv3/openapiv3/gen/openapi.yaml#L248-L259

Here is the client that uses the generated code:
https://github.com/veqryn/awesome-go-api/blob/c737ba1703d2ca30be0d898b17717eca8c70565f/protobufv3/openapiv3/ogen/main.go#L48-L49

When I curl the server, the response looks like this:
```shell
$ curl -vv -k -L localhost:8080/error
* Host localhost:8080 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:8080...
* Connected to localhost (::1) port 8080
> GET /error HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.7.1
> Accept: */*
>
* Request completely sent off
< HTTP/1.1 400 Bad Request
< Content-Type: application/json
< Date: Sat, 14 Sep 2024 06:05:49 GMT
< Content-Length: 306
<
* Connection #0 to host localhost left intact
{"code":3, "message":"This is an example error", "details":[{"@type":"type.googleapis.com/google.protobuf.Any", "value":{"@type":"type.googleapis.com/google.protobuf.DoubleValue", "value":224.92}}, {"@type":"type.googleapis.com/google.rpc.LocalizedMessage", "locale":"en-US", "message":"Fix your widget"}]}
```

Ogen seems to be unable to decode that response body into the rpcStatus object details.

### What did you expect to see?
No decode error.

### What did you see instead?
```
(*errors.wrapError)(0x140000b8b80)(decode response: default (code 400): decode application/json: decode RpcStatus: callback: decode field "details": callback: decode ProtobufAny: callback: decode field "locale": decode ProtobufAnyAdditionalItem: "{" expected: unexpected byte 34 '"' at 267)
```

**Comment by tdakkota** [comment]
`protobufAny` is defined as:
```json
{
  "type": "object",
  "properties": {
    "@type": {
      "type": "string"
    }
  },
  "additionalProperties": {
    "type": "object" // <-- all properties should be objects except @type
  }
}
```
and input is:
```json
{
  "@type": "type.googleapis.com/google.rpc.LocalizedMessage",
  "locale": "en-US", // <- string
  "message": "Fix your widget"
}
```
It seems for me that decoder works as intended. Error message might be  more clear, I guess.

**Comment by veqryn** [comment]
Hm...

The yaml was created by the gRPC Gateway, which only supports OpenAPI v2:
```yaml
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
```


I upgraded it to v3 using swagger-codegen, which turned it into this:
```yaml
    protobufAny:
      type: object
      properties:
        '@type':
          type: string
      additionalProperties:
        type: object
```

So I'm not an expert in OpenAPI.

I am guessing the instead of `additionalProperties: {}`, it should be `additionalProperties: true`, is that correct?

**Comment by tdakkota** [comment]
In OpenAPI 3, `additionalProperties: {}` is effectively the same as `additionalProperties: true`. It seems there is bug in swagger-codegen, it should not add `type: object`.

**Comment by veqryn** [comment]
Created issues here:
https://github.com/swagger-api/swagger-codegen/issues/12468
https://github.com/OpenAPITools/openapi-generator/issues/19596
https://github.com/grpc-ecosystem/grpc-gateway/issues/4724

**Comment by veqryn** [comment]
@tdakkota thx. I've got a workaround/hack for this to generate the correct v3, but now I'm running into this issue/feature-request https://github.com/ogen-go/ogen/issues/1313
