### ISSUE TITLE
feat(gen): adding support for handler interface splitting

### ISSUE THREAD

**Issue by utherbit** [ogen-go/ogen#1318]
### Description

When generating a large specification, implementing the handler interface is problematic.

I tried to solve this using inheritance to divide the implementation into several types, but this is not convenient because it cannot be explicitly stated that the type must correspond to the interface.

It seems to me that it would be convenient if the handler could be divided into several.

I'd like to know if others are having problems with too many handler methods and how you deal with it?

If anyone besides me is interested in this, we can try to think through this possibility in the comments.

### References

Using petstore as an example, I tried to write what it might look like:
[oas_server_gen.zip](https://github.com/user-attachments/files/17111464/oas_server_gen.zip)

**Comment by tdakkota** [comment]
It seems that [`x-ogen-operation-group`](https://github.com/ogen-go/ogen?tab=readme-ov-file#operation-groups) is exactly what you want.

**Comment by utherbit** [comment]
> It seems that [`x-ogen-operation-group`](https://github.com/ogen-go/ogen?tab=readme-ov-file#operation-groups) is exactly what you want.

This is what you need! unbelievable. Forgive me for my inattention and thank you very much
