### ISSUE TITLE
gen: support for paths relative to Server.URL

### ISSUE THREAD

**Issue by danilvpetrov** [ogen-go/ogen#462]
### Description

The OpenAPI Standard (v3.0.3) specifies that [`Paths Object`](https://swagger.io/specification/#paths-object) is a relative path to [`Server.URL`](https://swagger.io/specification/#server-object).  [`Server.URL`](https://swagger.io/specification/#server-object) might already contain a path that is further joint with the relatives paths according to the spec. `ogen-go/ogen` currently generates radix router not including the existing path in [`Server.URL`](https://swagger.io/specification/#server-object).

Would be it be possible to consider adding the support for existing paths in  [`Server.URL`](https://swagger.io/specification/#server-object) when generating path matching code in `oas_router_gen.go`?

### References

- [Open API Paths Object Spec](https://swagger.io/specification/#paths-object)
- [Open API Server Object Spec](https://swagger.io/specification/#server-object)

**Comment by deslittle** [comment]
This page also describes the full URL as being a concatenation of the server URL and path.
https://swagger.io/docs/specification/api-host-and-base-path/

Would be great if the generated router could match the server URL first, then the path.

**Comment by DavidFeng** [comment]
Before this was implemented, you can use path without /api/v1 ,and use a path rewrite middleware to do this for you, I am using chi with this project

**Comment by ernado** [comment]
```yaml
openapi: 3.0.3
servers:
  - url: /api/v1
info:
  version: 1.0.0
  title: Test API
paths:
  /dashboard/totals:
  /dashboard/history:
```
Is really better, let's implement it.

**Comment by tdakkota** [comment]
It will be a bit confusing why router does not serve paths which are defined in the spec.

Spec can define multiple servers. If it does, and we implement this feature, the full path will be ambiguous.
```yaml
# What path should be used for /download?
openapi: 3.0.0
info:
  title: Example
  version: 0.1.0
servers:
  - url: https://example.com/api/v1
  - url: https://test.example.com/api/v1
  - url: http://localhost:8080/v1
paths:
  /download:
    get:
      responses:
        '200':
          description: Response
          content:
            "*/*":
              schema:
                type: string
                format: binary
```
Also, `Path Item Object` or `Operation Object` can define an alternative server list.
```yaml
/upload:
  servers:
    - url: https://upload.example.com
    - url: https://test.example.com
  post:
    requestBody:
      content:
        "*/*":
          schema:
            type: string
            format: binary
    responses:
      '200':
        description: Response
```

On the other hand, path prefix can easily be trimmed by reverse proxy or [`http.StripPrefix`](https://pkg.go.dev/net/http#StripPrefix).
```go
server, err := api.NewServer(serviceImpl{})
if err != nil {
panic(err)
}
http.Handle("/api/v1/", http.StripPrefix("/api/v1/", server))
```

**Comment by ernado** [comment]
Now I see, agree.

AFAIK this is not defined explicitly by openapi scheme and probably is not used in the wild, so I'll close it for now.

Please use possible workarounds.

**Comment by deslittle** [comment]
Yes I have used the `http.StripPrefix("/api/v1/", server)` method as a workaround also and it works. 

I guess my main issue is compatibility with other tools such as Swagger UI where you can choose which server or server version to test against.

Perhaps it could be that by convention, ogen matches relative paths in the server object only?

Ideally you may also want to have something like this for certain routes to support staged migrations:

```
# What path should be used for /download?
openapi: 3.0.0
info:
  title: Example
  version: 0.1.0
servers:
  - url: /api/v2
paths:
  /download:
    servers:
      - url: /api/v1
      - url: /api/v2
```

This would mean ogen would need to use the base server list as a default and overwrite the paths for any paths that have it explicitly defined.

<img width="691" alt="SwaggerUIServerExample" src="https://user-images.githubusercontent.com/4271492/180913447-9e07711c-9be3-4d0f-a064-e57aeeaa7116.png">

**Comment by zwpaper** [comment]
if anyone meet this issue, there is a server option can handle this

```golang
srv, err := api.NewServer(svc, svc, api.WithPathPrefix("/v2"))
```

**Comment by NielsCodes** [comment]
@zwpaper thank you! I've been browsing the docs and thought I was going crazy that there was no such option.
