### ISSUE TITLE
go-linter: unnecessary type arguments in `_handlers_gen.go`

### ISSUE THREAD

**Issue by exu** [ogen-go/ogen#625]
### What version of ogen are you using?

```bash
ogen version v0.52.1 (built with go1.19.1) darwin/arm64
```

### Can this issue be reproduced with the latest version?

Yes

### What did you do?

Generate based on OpenAPI spec 

### What did you expect to see?

No linter errors

### What did you see instead?

<img width="495" alt="image" src="https://user-images.githubusercontent.com/30776/195813659-556d8a5b-0665-40d0-9b6f-7e17b1d62500.png">

**Comment by ernado** [comment]
Generated code should be skipped by linters entirely.

**Comment by tdakkota** [comment]
We cannot rely on type inference here, so we pass type parameters explicitly. If we do, in some scenario type checker may fail to infer type parameters.
