### ISSUE TITLE
complex schema merging: error doesn't specify where this is or what it means

### ISSUE THREAD

**Issue by Southclaws** [ogen-go/ogen#681]
### What version of ogen are you using?

v0.54.1

### Can this issue be reproduced with the latest version?

Yes

### What did you do?

I'm interested in upgrading our OpenAPI codegen tooling from deepmap/oapi-codegen to ogen as it seems more maintained and produces some nicer code. I ran it on our spec and it produced this error:

```go
Feature "complex schema merging" is not implemented yet.
Try to run ogen with --debug.ignoreNotImplemented "complex schema merging" or with --debug.noerr to skip unsupported operations.
```

Now I'm not sure, from the error, what the implications of this are. I don't know what specific schema merging it's referring to (`allOf`?, `discriminator`? `oneOf`?) or where it is (a line number in the spec).

But aside from that, I'm also not sure what the implications of using `--debug.ignoreNotImplemented` are. Will my generated server still work? Will it partially work? Will the code just be less type-safe or will an entire path be omitted?

I couldn't find anything in the docs about this specific error or any reference to the phrase "complex schema merging".

Thanks! Looking forward to switching to this if I can figure out if it's fine to ignore this until it's implemented!

**Comment by Southclaws** [comment]
Alright after trying with the flag I found that it just omits these endpoints entirely and the line numbers show once you add `--debug.ignoreNotImplemented`.

I make heavy use of `allOf` and `discriminator` and it seems to be these ones causing the errors.

Is there anything I can do to help implement this? What's the blocker and how complex is it?

**Comment by shadowspore** [comment]
Current allOf implementation relies on jsonschema ```type``` field.
Most likely some of your schemes in allOf does not specify it
```yml
allOf: # will not work
- maxLength: 15
- nullable: true
- type: string

allOf: # should work
- type: string
  maxLength: 15
- type: string
  nullable: true
- type: string
```

We need to improve or rewrite [schema merge code](https://github.com/ogen-go/ogen/blob/e501483a49bc0a51ee308bd3eb21aeba9016dcf5/gen/schema_gen_sum.go#L461) to remove this limitation.

Also there is a ```--infer-types``` flag.
It allows ogen to guess jsonschema types based on type-specific validation fields if they are set.

**Comment by Southclaws** [comment]
Ah yes I missed this entirely, I finally ran a linter on our spec and realised there are quite a few types that were left to be inferred as `any` instead of explicitly marking them as `object` or `array`. Some of the tooling is quite lenient, and some of it is quite strict so I'll be defaulting to strict from now on to avoid confusion like this!

**Comment by shadowspore** [comment]
> It seems to be working quite well now anyway

Glad to see that it works

> Does ogen work with discriminator, do you think it would be worth me adding it back to our spec tomorrow?

Ogen works with discriminators (in general), so you can try to generate schema with it, and see what happens
