### ISSUE TITLE
gen: Extra struct field tags for ORM or validation libraries

### ISSUE THREAD

**Issue by pgillich** [ogen-go/ogen#689]
### Description

It would be nice to add extra Go field tags to the generated struct field, similar to **oapi-codegen**. This is useful for interfacing with tag based ORM or validation libraries. The extra tags that are added are in addition to the regular json tags that are generated.

### References

* https://spec.openapis.org/oas/v3.1.0#specification-extensions
* [oapi-codegen](https://github.com/deepmap/oapi-codegen#extensions)
* https://github.com/ogen-go/ogen/blob/main/gen/_template/schema/struct.tmpl#L9
* https://github.com/ogen-go/ogen/blob/main/jsonschema/extensions.go
* https://github.com/ogen-go/ogen/blob/main/gen/ir/field.go#L33

**Comment by tdakkota** [comment]
> This is useful for interfacing with tag based ORM or validation libraries. 

`ogen` generates a lot of definitions like optionals, enums and sum types, that wouldn't be properly handled by GORM or any validation library.

**Comment by pgillich** [comment]
> > This is useful for interfacing with tag based ORM or validation libraries.
> 
> `ogen` generates a lot of definitions like optionals, enums and sum types, that wouldn't be properly handled by GORM or any validation library.

The two worlds cannot be matched 100%, so only simple cases can be handled.

**Comment by tdakkota** [comment]
Closing as #718 was merged.
