### ISSUE TITLE
Client code: Incorrect URL Path concatenation

### ISSUE THREAD

**Issue by egor-gorlin-exinity** [ogen-go/ogen#814]
### What version of ogen are you using?

```bash
$ go list -m github.com/ogen-go/ogen
github.com/ogen-go/ogen v0.59.0
```

### Can this issue be reproduced with the latest version?

Yes

### What did you do?

I have generated a client code.

Created a new client using `NewClient()` with `serverURL` parameter equal to "http://my.service.dom/"

Invoked a method "/auth" of the client.

### What did you expect to see?

Request should have URL equal to "http://my.service.dom/auth"

### What did you see instead?

Resulting request had an URL "http://my.service.dom//auth"

### Bug reason

Client method is generated with the following code:
```golang
	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	u.Path += "/auth"
```

### Proposal

I would like to make a PR but first i want you to choose the solution:
1. Use `path.Join()` instead of `+=` concatenation for `u.Path` (seems to be the cleanest but may have some overhead)
2. User `path.Clean()` after the `u.Path` concatenation
3. Trim extra `/` from the `serverURL` parameter in `NewClient()` (not clean but introduces almost zero overhead)

**Comment by ernado** [comment]
Probably we must just trim trialing slash, cc @tdakkota
