### ISSUE TITLE
feat: use generics

### ISSUE THREAD

**Issue by ernado** [ogen-go/ogen#868]
```go
type Opt[T any] struct {
	Value T
	Set   bool
}

// OptInt32 is optional int32.
// For backward compatibility.
type OptInt32 = Opt[int32]
```

Like that:
https://github.com/ernado/ogen-generics/blob/main/generics.go

Should be backward compatible, if we generate type aliases.
In structures, use `Opt[T]` directly:

```go
type Wrapped struct {
	Str Opt[string]
}
```

This will work:
```go
var w Wrapped

var v OptStr
v.SetTo("foo")

w.Str = v
```

Moreover, we can create a container package in ogen, so we don’t write Opt[T] implementation every time.

**Comment by tdakkota** [comment]
Closing as infeasible for now.
