### ISSUE TITLE
gen: save swagger file next to generated api

### ISSUE THREAD

**Issue by fildenisov** [ogen-go/ogen#878]
Hi!
I am generating an api based on a swagger which contains imports (refs). 
`allow-remote` flag works fine for me, but I would like to save a single .yaml file (with all refs embedded) after generation to share it with the client's team. 

My suggestion is to add new flag 
`generateDocs = set.Bool("generate-docs", false, "Enables target[packageName].yml generation")`
if true, [packageName].yml will be generated in the target dir next to aos_*_gen.go files. 

PS: maybe .json file also

Thanks!

**Comment by ernado** [comment]
@tdakkota PTAL. Is there any intermediate representation so we can dump it like that?
