### ISSUE TITLE
gen: support `application/problem+json` Content-Type

### ISSUE THREAD

**Issue by p1ass** [ogen-go/ogen#883]
### Description

I request support for the `application/problem+json`  Content-Type.

Calling API server returns error responses as `application/problem+json` which is defined by [RFC 7808](https://datatracker.ietf.org/doc/html/rfc7807).
ogen does not currently support `application/problem+json`, so  when I use a generated API client, I got the below error:

```text
decode response: default (code 404): unexpected Content-Type: application/problem+json
```

### References

- https://datatracker.ietf.org/doc/html/rfc7807

**Comment by tdakkota** [comment]
1. OpenAPI Spec you're using should define response with a `application/problem+json` content type.
2. To avoid `Content types ... are unsupported` error, you may instruct ogen to decode `application/problem+json` like JSON by using `--ct-alias "application/problem+json=application/json"` option.
3. If response schema is properly defined, generated code whould be able to decode the problem object.

It doesn't seem like any special support needed.

**Comment by p1ass** [comment]
I missed that parameter.
It worked fine!
Thanks for letting me know!
