### ISSUE TITLE
unnecesary type arguments and infinite recursive call in generated code

### ISSUE THREAD

**Issue by docktermj** [ogen-go/ogen#921]
### What version of ogen are you using?

```bash
$ go list -m github.com/ogen-go/ogen

github.com/ogen-go/ogen v0.68.0
```

### Can this issue be reproduced with the latest version?

Yes

### What did you do?

Steps seen at https://github.com/docktermj/go-http/tree/9c64ead219ab39432c47020e28ff7e14ee975c4c#development

### What did you see instead?

When the generated code was reviewed in Visual Studio Code the following warnings were given:

**unnecesary type arguments infertypeargs**  One example:

https://github.com/docktermj/go-http/blob/9c64ead219ab39432c47020e28ff7e14ee975c4c/senzinghttpapi/oas_handlers_gen.go#L125-L127

**infinite recursive call (SA5007) go-staticcheck**  One example 

https://github.com/docktermj/go-http/blob/9c64ead219ab39432c47020e28ff7e14ee975c4c/senzinghttpapi/oas_validators_gen.go#L13-L18

All of the artifacts used in the generation can be seen at 

https://github.com/docktermj/go-http/tree/9c64ead219ab39432c47020e28ff7e14ee975c4c

**Comment by docktermj** [comment]
@tdakkota @ernado Thank you both!

**Comment by docktermj** [comment]
@tdakkota @ernado Unfortunately, version 0.68.1 did not fix the issue.   Was #922 part of 0.68.1?

**Comment by ernado** [comment]
@docktermj please try v0.68.2

**Comment by docktermj** [comment]
@ernado Yes, v0.68.2 fixes the issue.  Thank you very much!
