### ISSUE TITLE
bug: go vet complains of unreachable code in "Decode"

### ISSUE THREAD

**Issue by justenwalker** [ogen-go/ogen#955]
This line here

https://github.com/ogen-go/ogen/blob/0b6c77e2117cb72a961ccd20d6a67bce88b59f34/gen/_template/json/encoders_struct.tmpl#L180

is unreachable when this case

https://github.com/ogen-go/ogen/blob/0b6c77e2117cb72a961ccd20d6a67bce88b59f34/gen/_template/json/encoders_struct.tmpl#L174C27-L178

```go
            {{- else if $.DenyAdditionalProps }}
			return errors.Errorf("unexpected field %q", k)
			{{- else }}
			return d.Skip()
			{{- end }}
		}
```

is generated which causes `go vet` to complain

```
.../oas_json_gen.go:1294:3: unreachable code
```

**Comment by ernado** [comment]
Generated code should be excluded from linting.

**Comment by justenwalker** [comment]
@ernado 
> Generated code should be excluded from linting.

I saw previous PRs #327 and #329 that lead me to believe this was something the project cared about. 

If not; feel free to close.

**Comment by ernado** [comment]
Oh, you are right, thank you for pointing it and finding this issue.

I think we will eventually fix it, so let's keep it open.
