### ISSUE TITLE
feat: export self-contained spec

### ISSUE THREAD

**Issue by ernado** [ogen-go/ogen#991]
- [ ] Add flag to `ogen` command to export resolved self-contained (single file) spec (in json or in yaml, use file extension for distriminating)
- [ ] Add flag to embed resulting spec into generated code, so one can serve it with Swagger UI

**Comment by tdakkota** [comment]
Very similar to #878.

**Comment by ernado** [comment]
Forgot that it is already implemented.

Embedding can be solved by go:embed, so closing.
